localgov_base.settings:
  type: config_object
  label: 'LocalGov Base settings'
  mapping:
    localgov_base_remove_css:
      type: boolean
      label: 'Remove CSS libraries from base theme.'
    localgov_base_remove_js:
      type: boolean
      label: 'Remove JS libraries from base theme.'
    localgov_base_add_unpublished_background_colour:
      type: boolean
      label: 'Add background colour to unpublished content.'
    localgov_base_add_draft_note_to_unpublished_content:
      type: boolean
      label: 'Add "[Draft]" to title of unpublished content.'
    localgov_base_add_archived_note_to_archived_content:
      type: boolean
      label: 'Add "[Archived]" to title of archived content.'
    localgov_base_header_behaviour:
      type: string
      label: 'Header behaviour'
      description: 'Choose whether the header should be sticky or not.'
      constraints:
        Regex: '^(default|sticky|appears_on_scroll)$'
    localgov_base_localgov_guides_stacked_heading:
      type: boolean
      label: 'Stacked heading'
      description: 'Choose whether the heading should be stacked or not.'
    localgov_base_localgov_guides_vertical_navigation:
      type: boolean
      label: 'Vertical navigation'
      description: 'Choose whether the navigation should be vertical or not.'
    localgov_base_mobile_breakpoint_js:
      type: string
      label: 'Mobile breakpoint for JS'
      description: 'The mobile breakpoint for JS. This is used to determine when to apply mobile styles.'
      default_value: '768'
