name: Test localgovdrupal/localgov_events drupal-module

on:
  push:
    branches:
      - '3.x'
  pull_request:
    branches:
      - '3.x'
  workflow_dispatch:

jobs:
  tests:
    uses: localgovdrupal/localgov_shared_workflows/.github/workflows/test-module.yml@1.x
    with:
      project: 'localgovdrupal/localgov_events'
      project_path: 'web/modules/contrib/localgov_events'
